base:
  seed: 0
  num_workers: 6

wandb:
  project: 'DLPLAB5'
  entity: 'kyoyachuan'
  name: 'baseline_wgan_ori_v2'

generator:
  code_dim: 128
  cond_dim: 128
  self_attention: false
  cbn: false

discriminator:
  self_attention: false
  projection: false

trainer:
  checkpoint_path: 'baseline_wgan_ori_v2'
  save_interval: 50
  log_image_interval: 10
  test_labels_path: 'test.json'
  loss_type: 'wasserstein'
  clamp_values: 0.01
  niters: 300
  epoch_size: 500
  n_d: 1
  lr_g: 2e-4
  lr_d: 5e-5
  batch_size: 128