base:
  seed: 1
  num_workers: 6

wandb:
  project: 'DLPLAB5'
  entity: 'kyoyachuan'
  name: 'hinge'

generator:
  code_dim: 128
  cond_dim: 128
  self_attention: false
  cbn: false

discriminator:
  self_attention: false
  projection: false

trainer:
  checkpoint_path: 'hinge'
  save_interval: 10
  test_labels_path: 'test.json'
  loss_type: 'hinge'
  clamp_values: 0.01
  niters: 200
  epoch_size: 1000
  n_d: 1
  lr_g: 1e-4
  lr_d: 4e-4
  batch_size: 64
