base:
  seed: 1
  num_workers: 6

wandb:
  project: 'DLPLAB5'
  entity: 'kyoyachuan'
  name: 'self_attention_minimax'

generator:
  code_dim: 128
  cond_dim: 64
  self_attention: true
  cbn: false

discriminator:
  self_attention: true
  projection: true

trainer:
  checkpoint_path: 'self_attention_minimax'
  save_interval: 50
  log_image_interval: 20
  test_labels_path: 'test.json'
  loss_type: 'minimax'
  clamp_values: 0.01
  niters: 500
  epoch_size: 1000
  n_d: 1
  lr_g: 1e-4
  lr_d: 4e-4
  batch_size: 64
